import { createHash } from 'node:crypto';

const IDENTIFIER = /^[a-z_][a-z0-9_]*$/;
const SAFE_ACTIONS = new Set(['cascade', 'restrict', 'set null', 'no action']);
const GENERATED_HEADER = 'Generated by tools/schema-orm-codegen.mjs. DO NOT EDIT.';

function fail(message) {
  throw new Error(message);
}

function stableStringify(value) {
  const sort = (input) => {
    if (Array.isArray(input)) return input.map(sort);
    if (input && typeof input === 'object') {
      return Object.fromEntries(Object.keys(input).sort().map((key) => [key, sort(input[key])]));
    }
    return input;
  };
  return `${JSON.stringify(sort(value), null, 2)}\n`;
}

function sha256(text) {
  return createHash('sha256').update(text).digest('hex');
}

function snakeCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[-.\s]+/g, '_')
    .replace(/__+/g, '_')
    .toLowerCase();
}

function pascalCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function camelCase(value) {
  const p = pascalCase(value);
  return p ? p.charAt(0).toLowerCase() + p.slice(1) : p;
}

function pluralize(value) {
  if (value.endsWith('s')) return `${value}Records`;
  if (value.endsWith('y') && !/[aeiou]y$/i.test(value)) return `${value.slice(0, -1)}ies`;
  return `${value}s`;
}

function rustName(value) {
  const candidate = snakeCase(value);
  const reserved = new Set(['type', 'match', 'ref', 'self', 'crate', 'super', 'mod', 'use', 'enum', 'struct', 'fn', 'impl', 'async', 'await', 'move', 'where', 'loop', 'in', 'as', 'dyn']);
  return reserved.has(candidate) ? `r#${candidate}` : candidate;
}

function tsName(value) {
  const candidate = camelCase(value);
  const reserved = new Set(['class', 'function', 'default', 'export', 'import', 'delete', 'new', 'var', 'let', 'const', 'extends', 'implements', 'interface', 'package', 'private', 'public', 'protected', 'static']);
  return reserved.has(candidate) ? `${candidate}Value` : candidate;
}

function goName(value) {
  const candidate = pascalCase(value)
    .replace(/Api/g, 'API')
    .replace(/Vcs/g, 'VCS')
    .replace(/Sha256/g, 'SHA256')
    .replace(/Url/g, 'URL')
    .replace(/Ip/g, 'IP')
    .replace(/Id(?=$|[A-Z])/g, 'ID');
  const reserved = new Set(['Type', 'Map', 'String', 'Error', 'Any']);
  return reserved.has(candidate) ? `${candidate}Value` : candidate;
}

function dartName(value) {
  const candidate = camelCase(value);
  const reserved = new Set(['class', 'enum', 'extension', 'mixin', 'with', 'on', 'base', 'interface', 'final', 'sealed', 'when', 'switch', 'case', 'default', 'import', 'export', 'part']);
  return reserved.has(candidate) ? `${candidate}Value` : candidate;
}

function assertIdentifier(value, label) {
  if (!IDENTIFIER.test(value)) fail(`${label} must be a safe snake_case identifier: ${value}`);
}

function normalizedTypes(property) {
  const raw = property.type;
  const values = Array.isArray(raw) ? raw : raw ? [raw] : [];
  return values.filter((value) => value !== 'null');
}

function propertyKind(property) {
  const types = normalizedTypes(property);
  if (types.length !== 1) fail(`property must have exactly one non-null JSON type: ${JSON.stringify(property)}`);
  return types[0];
}

function isNullable(property, required) {
  return !required || (Array.isArray(property.type) && property.type.includes('null'));
}

function normalizeSchema(schema) {
  if (!schema || typeof schema !== 'object') fail('schema must be an object');
  if (schema.$schema !== 'https://json-schema.org/draft/2020-12/schema') {
    fail('schema must use JSON Schema draft 2020-12');
  }
  if (!schema.$defs || typeof schema.$defs !== 'object') fail('schema.$defs is required');
  const root = schema['x-lib-core'];
  if (!root || typeof root !== 'object') fail('schema.x-lib-core is required');
  if (!root.product || !root.interfaces?.repository) fail('x-lib-core.product and x-lib-core.interfaces.repository are required');

  const entities = [];
  for (const [name, definition] of Object.entries(schema.$defs)) {
    const db = definition['x-db'];
    if (!db?.table) continue;
    if (definition.type !== 'object') fail(`${name} must be an object schema`);
    assertIdentifier(db.table, `${name}.x-db.table`);
    const properties = definition.properties ?? {};
    const required = new Set(definition.required ?? []);
    const primaryKey = db.primaryKey ?? (properties.id ? ['id'] : []);
    if (!Array.isArray(primaryKey) || primaryKey.length === 0) fail(`${name} requires x-db.primaryKey or an id property`);

    const fields = Object.entries(properties).map(([fieldName, property]) => {
      const fieldDb = property['x-db'] ?? {};
      const column = fieldDb.column ?? snakeCase(fieldName);
      assertIdentifier(column, `${name}.${fieldName}.x-db.column`);
      const requiredField = required.has(fieldName);
      const kind = propertyKind(property);
      if (fieldDb.references) {
        if (!schema.$defs[fieldDb.references.entity]) fail(`${name}.${fieldName} references unknown entity ${fieldDb.references.entity}`);
        if (!schema.$defs[fieldDb.references.entity].properties?.[fieldDb.references.field]) {
          fail(`${name}.${fieldName} references unknown field ${fieldDb.references.entity}.${fieldDb.references.field}`);
        }
        for (const actionKey of ['onDelete', 'onUpdate']) {
          const action = fieldDb.references[actionKey];
          if (action && !SAFE_ACTIONS.has(action.toLowerCase())) fail(`${name}.${fieldName} has unsupported ${actionKey}: ${action}`);
        }
      }
      return {
        name: fieldName,
        column,
        property,
        db: fieldDb,
        kind,
        required: requiredField,
        nullable: isNullable(property, requiredField),
      };
    });
    const fieldMap = new Map(fields.map((field) => [field.name, field]));
    for (const key of primaryKey) if (!fieldMap.has(key)) fail(`${name} primary key references unknown field ${key}`);

    const indexes = (db.indexes ?? []).map((index, indexNumber) => {
      if (!Array.isArray(index.fields) || index.fields.length === 0) fail(`${name} index ${indexNumber} requires fields`);
      for (const field of index.fields) if (!fieldMap.has(field)) fail(`${name} index references unknown field ${field}`);
      const indexName = index.name ?? `${db.table}_${index.fields.map((field) => fieldMap.get(field).column).join('_')}_${index.unique ? 'uq' : 'idx'}`;
      assertIdentifier(indexName, `${name} index name`);
      return { ...index, name: indexName };
    });

    const checks = (db.checks ?? []).map((check) => {
      assertIdentifier(check.name, `${name} check name`);
      if (!check.expression || typeof check.expression !== 'string') fail(`${name}.${check.name} requires an expression`);
      return check;
    });

    entities.push({
      name,
      module: snakeCase(name),
      className: pascalCase(name),
      interfaceType: definition['x-interface']?.type ?? name,
      table: db.table,
      description: definition.description ?? '',
      fields,
      fieldMap,
      primaryKey,
      indexes,
      checks,
    });
  }
  if (entities.length === 0) fail('schema contains no x-db.table entity definitions');
  const names = new Set(entities.map((entity) => entity.name));
  if (names.size !== entities.length) fail('duplicate entity names');
  const tables = new Set(entities.map((entity) => entity.table));
  if (tables.size !== entities.length) fail('duplicate table names');
  return { schema, root, entities, entityMap: new Map(entities.map((entity) => [entity.name, entity])) };
}


function topologicalEntities(model) {
  const remaining = new Map(model.entities.map((entity) => [entity.name, entity]));
  const result = [];
  while (remaining.size) {
    const ready = [...remaining.values()].filter((entity) => entity.fields.every((field) => !field.db.references || !remaining.has(field.db.references.entity)));
    if (ready.length === 0) return model.entities;
    ready.sort((a, b) => a.name.localeCompare(b.name));
    for (const entity of ready) {
      result.push(entity);
      remaining.delete(entity.name);
    }
  }
  return result;
}


export {
  GENERATED_HEADER,
  camelCase,
  dartName,
  fail,
  goName,
  normalizeSchema,
  pascalCase,
  pluralize,
  rustName,
  sha256,
  snakeCase,
  stableStringify,
  topologicalEntities,
  tsName,
};
